apiVersion: v1
kind: ServiceAccount
metadata:
  name: fasttechfoods-auth-workload-identity-sa
  namespace: fasttechfoods
  annotations:
    azure.workload.identity/client-id: "e9c79217-2087-4d18-b4ad-bc2f241e3114"
  labels:
    azure.workload.identity/use: "true"
