# SecretProviderClass para buscar secrets do Azure Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fasttechfoods-auth-secrets-provider
  namespace: fasttechfoods
spec:
  provider: azure
  secretObjects:
  - secretName: fasttechfoods-auth-secrets
    type: Opaque
    data:
    - objectName: SEC-JWT-SECRET
      key: JWT_SECRET
    - objectName: SEC-CONNECTION-STRING-PG-DATABASE
      key: CONNECTION_STRING_DATABASE
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "e9c79217-2087-4d18-b4ad-bc2f241e3114"
    keyvaultName: "kv-fastechfood"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: SEC-JWT-SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: SEC-CONNECTION-STRING-PG-DATABASE
          objectType: secret
          objectVersion: ""
    tenantId: "1b4119a8-1ec6-4bec-98d9-4821b933e35b"
